#!/bin/sh

go fmt ./...
go vet ./...
go vet -vettool=$(which shadow) ./...

# MixedCaps, ALL_CAPS: 先頭大文字や、Mongo Collection名など許容しているため省く
# CmsMstSettingCategory: constの量が多すぎるのと、見た目的に無い方が見やすそうなため、例外的に省く
golint ./... | grep -v "don't use MixedCaps" | grep -v "don't use ALL_CAPS in Go names" | grep -v "don't use an underscore in package name" | grep -v "CmsMstSettingCategory should have comment" && echo && exit 1 || true

${HOME}/staticcheck ./...
echo '☆★☆★　check all green. success.　☆★☆★'
